
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---
- name: Ensure PIP
  become: yes
  apt:
    name: python-pip
    state: present

- name: Ensure Prerequisites
  become: yes
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - maasclient==0.3
    - requests_oauthlib
    - ipaddress

- name: Ensure SSH Key
  maas_sshkey:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    sshkey: '{{maas.user_sshkey}}'
    state: present

- name: Ensure Administrative Zone
  maas_zone:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    name: administrative
    state: present

- name: Ensure Cluster
  maas_cluster:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    name: 'Cluster master'
    status: enabled
    domain: '{{maas.domain}}'

- name: Ensure Management Interface
  maas_cluster_interface:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    cluster_name: 'Cluster master'
    name: '{{interfaces.management}}'
    interface: '{{interfaces.management}}'
    management: dhcpdns
    ip: "{{networks.management | ipaddr(1) | ipaddr('address')}}"
    subnet_mask: "{{networks.management | ipaddr('netmask')}}"
    broadcast_ip: "{{networks.management | ipaddr('broadcast')}}"
    ip_range_low: '{{ranges.management.low}}'
    ip_range_high: '{{ranges.management.high}}'
    state: present

- name: Ensure Subnet Configuration
  maas_subnet:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    name: '{{networks.management}}'
    gateway_ip: "{{networks.management | ipaddr(1) | ipaddr('address')}}"
    dns_servers: "{{networks.management | ipaddr(1) | ipaddr('address')}}"

- name: Ensure Upstream DNS Server
  maas:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    upstream_dns: '{{maas.upstream_dns}}'
    state: present

- name: Set Kernel options for performance
  maas:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    kernel_opts: '{{maas.kernel_opts}}'
    state: present

- name: Ensure Boot Resources
  maas_boot_resource:
    key: '{{apikey.stdout}}'
    maas: 'http://{{mgmt_ip_address.stdout}}/MAAS/api/1.0'
    state: import
